# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
"""Render a validated :class:`~app.modules.module_builder.spec.ModuleSpec` into files.

Deterministic and total: the same spec renders the same bytes, and a spec that
validated always renders. No assistant is involved at this layer, which is why
what lands on a user's server is reviewable in the ordinary way.

What is rendered is a real module by the platform's own conventions -
manifest, models, schemas, repository, service, router, permissions,
validators, locales and tests - so the loader, the permission registry and the
validation engine pick it up with no special case for having been generated.

The user interface is deliberately not a React page. The frontend is a
compiled bundle, so a module installed at runtime cannot add a compiled screen
without a rebuild, and pretending otherwise would ship half a module. Instead
every generated module serves its own spec at ``<url_prefix>/ui-spec`` and the
core frontend renders list, detail and form from it. One generic screen that is
always in step beats a generated one that cannot be installed.
"""

from __future__ import annotations

import json
import re
import unicodedata
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from app.modules.module_builder.links import LINK_TARGETS
from app.modules.module_builder.spec import STATUS_CODE_MAX, STATUS_COLUMN, STATUS_RULE_CODE, FieldSpec, ModuleSpec

HEADER = """\
# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
"""

# Marks a file as machine-written, so a person reading it in a diff knows where
# it came from and that editing it by hand is a decision rather than an
# accident. Deliberately not a timestamp: a regenerated file that differs only
# by the second it was written would show up as a change in every review.
GENERATED_NOTE = (
    "# Generated by the OpenConstructionERP module builder from a module\n"
    "# specification. Edits are kept: the builder never overwrites a module it\n"
    "# did not just create. To change the shape, change the spec and generate\n"
    "# a new version.\n"
)

# Written into every spec.json, so an installed module says which generator
# rendered its code. The version moves when already-installed modules need
# their code rendered again, which ``refresh.refresh_installed`` does at
# startup for every module stamped with an older one.
#
#   1  the first generator. Its router checked the module permission only, so
#      a project-scoped module served every project's records to anyone
#      holding ``<key>.read``.
#   2  project-scoped routes also check access to the record's project.
#   3  names and descriptions are escaped where they land in docstrings and
#      string literals. Before, a name holding quotes could end the string
#      it was written into and put code of its own in the module.
GENERATOR_NAME = "openconstructionerp.module_builder"
GENERATOR_VERSION = 3
GENERATOR_STAMP = f"{GENERATOR_NAME}/{GENERATOR_VERSION}"

# The exception to GENERATED_NOTE, carried by the three files a newer builder
# may render again. Kept out of GENERATED_NOTE itself: the files that hold the
# table definition must render byte for byte as they always have, or a
# refresh would refuse them.
REFRESHED_NOTE = (
    "# This file is the exception: when a newer builder fixes the code it\n"
    "# renders here, it renders it again from spec.json at startup. The copy it\n"
    "# replaces is kept under _module_builder/backups in the module folder.\n"
)

# SQLAlchemy column type per field type, and the Python annotation that goes
# with it. Money is Numeric, never float: a rate that loses cents is a defect
# the user finds in an invoice.
COLUMN_TYPES: dict[str, tuple[str, str]] = {
    "text": ("String(255)", "str"),
    "long_text": ("Text", "str"),
    "integer": ("Integer", "int"),
    "number": ("MoneyType(18, 4)", "Decimal"),
    "money": ("MoneyType(18, 2)", "Decimal"),
    "date": ("Date", "date"),
    "datetime": ("DateTime(timezone=True)", "datetime"),
    "boolean": ("Boolean", "bool"),
    "select": ("String(64)", "str"),
    "link": ("GUID()", "uuid.UUID"),
}

# Where each column type is imported from. Computed rather than emitted as a
# fixed block: a spec with no dates and no numbers would otherwise render
# imports nothing uses, and ruff refuses the module the builder just wrote.
_SQLALCHEMY_NAMES = {"String", "Text", "Integer", "Date", "DateTime", "Boolean"}


# ── user text in generated code ─────────────────────────────────────────────
#
# Names, labels and descriptions are whatever a person or the assistant wrote,
# in any of the platform's languages, where quotes and backslashes are
# ordinary. They reach generated Python in two kinds of place: inside a
# docstring, and as a string literal. Each kind has one helper below, and
# every such place goes through it (``!r`` is the third, already safe way).
# Banning the characters instead would refuse names people really use.
#
# Both helpers return text that was already safe unchanged, byte for byte. A
# module rendered before them renders the same files after, which is what lets
# a refresh rewrite its code instead of refusing a table it no longer matches.

# Characters written as escapes rather than as themselves: control characters,
# line and paragraph separators, and lone surrogates (which cannot even be
# written to a UTF-8 file).
_ESCAPED_CATEGORIES = frozenset({"Cc", "Cs", "Zl", "Zp"})


def _escape(char: str) -> str:
    code = ord(char)
    return f"\\x{code:02x}" if code < 0x100 else f"\\u{code:04x}"


def _doc(text: str) -> str:
    """User text for the inside of a triple-double-quoted docstring.

    A backslash is doubled, so it reads as itself rather than starting an
    escape. In a run of three or more double quotes, which would end the
    docstring, every quote is escaped. Characters in
    :data:`_ESCAPED_CATEGORIES` become escapes, except the newline and tab a
    description may hold.
    """
    text = text.replace("\\", "\\\\")
    text = "".join(
        _escape(c) if unicodedata.category(c) in _ESCAPED_CATEGORIES and c not in "\n\t" else c for c in text
    )
    return re.sub(r'"{3,}', lambda run: '\\"' * len(run.group()), text)


def _lit(text: str) -> str:
    """User text as a double-quoted Python string literal.

    JSON's string syntax is a subset of Python's, so ``json.dumps`` does the
    quoting; what it leaves raw from :data:`_ESCAPED_CATEGORIES` is escaped on
    top. Plain text comes out as ``"text"``, as the templates always wrote it.
    """
    quoted = json.dumps(text, ensure_ascii=False)
    return "".join(_escape(c) if unicodedata.category(c) in _ESCAPED_CATEGORIES else c for c in quoted)


def _first_party(*imports: str) -> str:
    """``from app... import ...`` lines in the order ruff's isort wants them.

    Used where links or features add an import to a block whose other lines
    are fixed, so the added line lands where a reviewer running ruff expects.
    """
    return "".join(sorted(imports, key=lambda line: line.split()[1]))


@dataclass(frozen=True)
class GeneratedFile:
    """One rendered file, relative to the module directory."""

    path: str
    content: str

    @property
    def lines(self) -> int:
        return self.content.count("\n")


def render(spec: ModuleSpec) -> list[GeneratedFile]:
    """Render the whole module. Order is stable so diffs are readable."""
    return [
        GeneratedFile("__init__.py", _init(spec)),
        GeneratedFile("manifest.py", _manifest(spec)),
        GeneratedFile("spec.json", _spec_json(spec)),
        GeneratedFile("models.py", _models(spec)),
        GeneratedFile("schema.py", _schema(spec)),
        GeneratedFile("schemas.py", _schemas(spec)),
        GeneratedFile("validators.py", _validators(spec)),
        GeneratedFile("permissions.py", _permissions(spec)),
        GeneratedFile("repository.py", _repository(spec)),
        GeneratedFile("service.py", _service(spec)),
        GeneratedFile("router.py", _router(spec)),
        GeneratedFile("locales/en.json", _locale(spec)),
        GeneratedFile("tests/__init__.py", ""),
        GeneratedFile("tests/conftest.py", _tests_conftest()),
        GeneratedFile(f"tests/test_{spec.key}.py", _tests(spec)),
        GeneratedFile("README.md", _readme(spec)),
    ]


def write(spec: ModuleSpec, root: Path) -> list[Path]:
    """Render and write into ``root/<key>/``. Refuses to overwrite.

    A module directory that already exists is never written into. Overwriting
    is how a user loses the edits they made to a generated module, and the
    builder has no way to tell its own output from work done since.

    The exceptions are :mod:`~app.modules.module_builder.refresh`, which
    renders the code files again when the generator version moves, and
    :mod:`~app.modules.module_builder.upgrade`, which writes a whole new
    version beside the module and swaps it in. Both keep the copies they
    replace.
    """
    target = root / spec.key
    if target.exists():
        raise FileExistsError(
            f"{target} already exists. Uninstall the module or choose another key; "
            "the builder does not overwrite a directory it did not just create."
        )
    written: list[Path] = []
    try:
        for item in render(spec):
            path = target / item.path
            path.parent.mkdir(parents=True, exist_ok=True)
            # newline="\n" on purpose. The default translates to CRLF on
            # Windows, and a module generated on one operating system would
            # then differ byte for byte from the same spec generated on
            # another - which turns every cross-platform diff into noise.
            path.write_text(item.content, encoding="utf-8", newline="\n")
            written.append(path)
    except Exception:
        # A half-written module is worse than none: the loader would import
        # what landed and fail somewhere unrelated to the cause.
        import shutil

        shutil.rmtree(target, ignore_errors=True)
        raise
    return written


# ── renderers ───────────────────────────────────────────────────────────────


def _init(spec: ModuleSpec) -> str:
    """The package, and the startup hook the loader calls after importing it.

    Two things have to happen once the module is loaded and neither can happen
    at import time. Permissions must be registered, because a permission the
    registry has never heard of is denied to everyone except an administrator,
    and the module would then appear to work for whoever tested it and for
    nobody else. And the table has to exist, because a module installed at
    runtime has no migration to create it.
    """
    return f'''{HEADER}"""{_doc(spec.display_name)}.

{_doc(spec.description or "Generated by the OpenConstructionERP module builder.")}

Generated from a module specification. ``spec.json`` beside this file is the
description the code came from, and is what the interface renders the module's
screens out of.
"""

import logging

logger = logging.getLogger(__name__)


async def on_startup() -> None:
    """Register permissions and make sure the module's table is there.

    Called by the module loader once the package has been imported.
    """
    from app.database import engine
    from app.modules.{spec.key}.permissions import register_{spec.key}_permissions
    from app.modules.{spec.key}.schema import ensure_table

    register_{spec.key}_permissions()

    # A module installed at runtime lives outside the repository and therefore
    # outside Alembic, so nothing else will ever create this table. Checked
    # first, so this is a no-op on every start after the first.
    await ensure_table(engine)
    logger.info("{spec.module_name}: table %s is present", {spec.table_name!r})
'''


def _depends(spec: ModuleSpec) -> list[str]:
    """The modules this one needs: projects when scoped, and each link's owner."""
    depends = ["oe_projects"] if spec.entity.project_scoped else []
    for field in spec.link_fields:
        module = LINK_TARGETS[field.target].module
        if module not in depends:
            depends.append(module)
    return depends


def _manifest(spec: ModuleSpec) -> str:
    return f'''{HEADER}"""{_doc(spec.display_name)} module manifest."""

{GENERATED_NOTE}
from app.core.module_loader import InferenceDeclaration, InferenceRole, ModuleManifest

manifest = ModuleManifest(
    name={spec.module_name!r},
    version={spec.version!r},
    display_name={spec.display_name!r},
    description={spec.description!r},
    author={(spec.author or "Built with the OpenConstructionERP module builder")!r},
    category={spec.category!r},
    depends={_depends(spec)!r},
    auto_install=False,
    enabled=True,
    inference=InferenceDeclaration(
        role=InferenceRole.NONE,
        basis=(
            "Generated from a module specification as create, read, update and delete over one "
            "table. The generator emits no model call and no scoring of any kind, so this is a "
            "statement about the code as written rather than a guess about what it is for. "
            "Add inference here by hand and this declaration stops being true: change the role "
            "and say what is inferred, because the register this feeds is quoted outside the "
            "project."
        ),
    ),
)
'''


def _spec_json(spec: ModuleSpec) -> str:
    """The spec, kept beside the code that came from it.

    This is what the generic frontend renders from and what a later version of
    the builder reads to regenerate. Without it the module is only readable as
    Python, and the screen would have to be inferred from the ORM.
    """
    payload = spec.model_dump(mode="json")
    payload["generated_at"] = datetime.now(UTC).isoformat()
    payload["generator"] = GENERATOR_STAMP
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _models(spec: ModuleSpec) -> str:
    entity = spec.entity
    columns = {COLUMN_TYPES[f.type][0].split("(")[0] for f in entity.fields}
    annotations = {COLUMN_TYPES[f.type][1] for f in entity.fields}

    # Always present: the row carries created_at and updated_at whatever the
    # spec says, and both of those need DateTime, func and datetime.
    sqlalchemy_names = {"DateTime", "Index", "func"} | (columns & _SQLALCHEMY_NAMES)
    links = spec.link_fields
    status = spec.features.status
    if entity.project_scoped or links:
        sqlalchemy_names.add("ForeignKey")
    if status is not None:
        sqlalchemy_names.add("String")
    stdlib_datetime = {"datetime"} | (annotations & {"date"})

    lines = [
        HEADER,
        f'"""{_doc(spec.display_name)} ORM model.\n\nTable:\n    {spec.table_name}\n"""\n',
        GENERATED_NOTE,
        "import uuid",
        f"from datetime import {', '.join(sorted(stdlib_datetime))}",
    ]
    if "Decimal" in annotations:
        lines.append("from decimal import Decimal")
    lines += [
        "",
        f"from sqlalchemy import {', '.join(sorted(sqlalchemy_names))}",
        "from sqlalchemy.orm import Mapped, mapped_column",
        "",
    ]
    target_models = sorted({LINK_TARGETS[f.target].models for f in links})
    if target_models:
        # The foreign key names a table by string. Importing the module that
        # owns it puts that table on the shared metadata, so creating this
        # table resolves the key even when nothing else imported it first.
        lines.append("# The tables the link fields point at, so their foreign keys resolve.")
        lines += [f"import {models}  # noqa: F401" for models in target_models]
    if "MoneyType" in columns:
        # The house decimal column. Plain Numeric hands back a float on some
        # backends, and a rate that arrives as 1450.7499999 is a defect the
        # user finds in an invoice rather than in a test.
        lines.append("from app.core.db_types import MoneyType")
    lines += [
        "from app.database import GUID, Base",
        "",
        "",
        f"class {spec.class_name}(Base):",
        f'    """{_doc(entity.display_name)}."""',
        "",
        f"    __tablename__ = {spec.table_name!r}",
        "",
        "    id: Mapped[uuid.UUID] = mapped_column(GUID(), primary_key=True, default=uuid.uuid4)",
    ]
    if entity.project_scoped:
        lines.append(
            "    project_id: Mapped[uuid.UUID] = mapped_column(\n"
            '        GUID(), ForeignKey("oe_projects_project.id", ondelete="CASCADE"), nullable=False\n'
            "    )"
        )
    for field in entity.fields:
        if field.type == "link":
            # Nullable whatever the spec says. The record it points at belongs
            # to another module and may be deleted there; SET NULL keeps this
            # row and drops only the link, where NOT NULL would block that
            # delete or cascade it into this module's data. "Required" is the
            # create schema's to enforce.
            lines.append(
                f"    {field.name}: Mapped[uuid.UUID | None] = mapped_column(\n"
                f'        GUID(), ForeignKey("{LINK_TARGETS[field.target].table}.id", ondelete="SET NULL"), '
                "nullable=True, default=None\n"
                "    )"
            )
            continue
        column, annotation = COLUMN_TYPES[field.type]
        optional = "" if field.required else " | None"
        default = "" if field.required else ", default=None"
        lines.append(
            f"    {field.name}: Mapped[{annotation}{optional}] = mapped_column("
            f"{column}, nullable={not field.required}{default})"
        )
    if status is not None:
        first = status.states[0].code
        lines.append(
            f"    {STATUS_COLUMN}: Mapped[str] = mapped_column(\n"
            f"        String({STATUS_CODE_MAX}), nullable=False, default={first!r}, server_default={first!r}\n"
            "    )"
        )
    lines += [
        "    created_at: Mapped[datetime] = mapped_column(",
        "        DateTime(timezone=True), server_default=func.now(), nullable=False",
        "    )",
        "    updated_at: Mapped[datetime] = mapped_column(",
        "        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False",
        "    )",
        "",
        "    __table_args__ = (",
    ]
    if entity.project_scoped:
        lines.append(f'        Index("ix_{spec.table_name}_project", "project_id"),')
    lines.append(f'        Index("ix_{spec.table_name}_created", "created_at"),')
    for field in links:
        lines.append(f'        Index("ix_{spec.table_name}_{field.name}", "{field.name}"),')
    if status is not None:
        lines.append(f'        Index("ix_{spec.table_name}_{STATUS_COLUMN}", "{STATUS_COLUMN}"),')
    lines += [
        "    )",
        "",
    ]
    return "\n".join(lines)


def _schema(spec: ModuleSpec) -> str:
    """The module creates its own table.

    A module installed at runtime lives outside the repository, so it cannot
    carry an Alembic revision: a revision file in the instance's data directory
    is either invisible to ``alembic upgrade`` or, once it is made visible,
    collides with the repository's own head on the next platform upgrade. Both
    failures land on the user, and the second one lands on every user at once.

    So the table is created from the same model the code reads, scoped to that
    one table and checked first. That is idempotent across restarts and across
    reinstalls, and it touches nothing the platform owns.
    """
    return f'''{HEADER}"""Physical table for {_doc(spec.display_name)}.

Table:
    {spec.table_name}

A generated module is installed outside the repository and therefore outside
Alembic's history, so it creates its own table rather than carrying a revision
that would collide with the platform's head on the next upgrade. Creation is
scoped to this one table and checked first, which makes it safe to call on
every start.

The scoping goes through ``Table.create`` and ``Table.drop`` rather than
``MetaData.create_all(tables=[...])``. The ``tables`` argument filters tables
and nothing else: standalone sequences declared anywhere on the shared
metadata are still visited, so dropping this module's table that way would
take a sequence belonging to another module with it.
"""

{GENERATED_NOTE}
from typing import Any

from sqlalchemy import Table

from app.modules.{spec.key}.models import {spec.class_name}


def table() -> Table:
    """The one table this module owns."""
    return {spec.class_name}.__table__


def create_table(bind: Any) -> None:
    """Create the table on a synchronous connection or engine, if absent."""
    table().create(bind, checkfirst=True)


def drop_table(bind: Any) -> None:
    """Drop the table on a synchronous connection or engine, if present.

    Only the uninstall path calls this, and only when the operator asked for
    the data to go too. Uninstalling a module leaves its rows alone by default.
    """
    table().drop(bind, checkfirst=True)


async def ensure_table(engine: Any) -> None:
    """Create the table through an async engine. Safe to call repeatedly."""
    async with engine.begin() as connection:
        await connection.run_sync(create_table)


async def remove_table(engine: Any) -> None:
    """Drop the table through an async engine. Destroys the module's data."""
    async with engine.begin() as connection:
        await connection.run_sync(drop_table)
'''


def _pydantic_type(field: FieldSpec) -> str:
    _, annotation = COLUMN_TYPES[field.type]
    return annotation if field.required else f"{annotation} | None"


def _schemas(spec: ModuleSpec) -> str:
    entity = spec.entity
    create_fields = []
    read_fields = []
    update_fields = []
    for field in entity.fields:
        annotation = _pydantic_type(field)
        default = "" if field.required else " = None"
        create_fields.append(f"    {field.name}: {annotation}{default}")
        # A link reads back as None once the record it pointed at is deleted,
        # required or not: the column is SET NULL (see the model).
        read_fields.append(f"    {field.name}: {'uuid.UUID | None' if field.type == 'link' else annotation}")
        _, base = COLUMN_TYPES[field.type]
        update_fields.append(f"    {field.name}: {base} | None = None")
    status = spec.features.status
    if status is not None:
        # Optional on create: a new record starts in the first state.
        create_fields.append(f"    {STATUS_COLUMN}: str = {status.states[0].code!r}")
        update_fields.append(f"    {STATUS_COLUMN}: str | None = None")
        read_fields.append(f"    {STATUS_COLUMN}: str")

    project_create = "    project_id: uuid.UUID\n" if entity.project_scoped else ""
    project_read = "    project_id: uuid.UUID\n" if entity.project_scoped else ""

    return f'''{HEADER}"""{_doc(spec.display_name)} request and response schemas."""

{GENERATED_NOTE}
import uuid
from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401

from pydantic import BaseModel, ConfigDict


class {spec.class_name}Create(BaseModel):
    """Payload for creating one {_doc(entity.display_name.lower())}."""

    model_config = ConfigDict(extra="forbid")

{project_create}{chr(10).join(create_fields)}


class {spec.class_name}Update(BaseModel):
    """Partial update. Every field is optional; absent means unchanged."""

    model_config = ConfigDict(extra="forbid")

{chr(10).join(update_fields)}


class {spec.class_name}Read(BaseModel):
    """One {_doc(entity.display_name.lower())} as the API returns it."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
{project_read}{chr(10).join(read_fields)}
    created_at: datetime
    updated_at: datetime


class {spec.class_name}List(BaseModel):
    """A page of {_doc(entity.plural_name.lower())}."""

    items: list[{spec.class_name}Read]
    total: int
'''


def _validators(spec: ModuleSpec) -> str:
    checks = []
    for rule in spec.rules:
        field = rule.field
        if rule.kind == "required":
            condition = f"value.{field} is None or (isinstance(value.{field}, str) and not value.{field}.strip())"
        elif rule.kind == "positive":
            condition = f"value.{field} is not None and value.{field} <= 0"
        elif rule.kind == "not_future":
            condition = f"value.{field} is not None and _is_future(value.{field})"
        elif rule.kind == "range":
            parts = []
            if rule.min_value is not None:
                parts.append(f"value.{field} < {rule.min_value}")
            if rule.max_value is not None:
                parts.append(f"value.{field} > {rule.max_value}")
            condition = f"value.{field} is not None and ({' or '.join(parts)})"
        elif rule.kind == "one_of":
            options = [f.options for f in spec.entity.fields if f.name == field][0]
            condition = f"value.{field} is not None and value.{field} not in {options!r}"
        else:  # order
            condition = (
                f"value.{field} is not None and value.{rule.other_field} is not None "
                f"and value.{field} > value.{rule.other_field}"
            )
        checks.append(
            f"    if {condition}:\n"
            f"        findings.append(\n"
            f"            Finding(\n"
            f"                code={rule.code!r},\n"
            f"                message={rule.message!r},\n"
            f"                field={field!r},\n"
            f"                severity={rule.severity!r},\n"
            f"            )\n"
            f"        )"
        )
    if spec.features.status is not None:
        codes = tuple(spec.status_codes)
        message = f"Status must be one of: {', '.join(codes)}."
        checks.append(
            f"    if value.{STATUS_COLUMN} not in {codes!r}:\n"
            f"        findings.append(\n"
            f"            Finding(\n"
            f"                code={STATUS_RULE_CODE!r},\n"
            f"                message={message!r},\n"
            f"                field={STATUS_COLUMN!r},\n"
            f"                severity='error',\n"
            f"            )\n"
            f"        )"
        )

    return f'''{HEADER}"""{_doc(spec.display_name)} validation rules.

Validation is part of the workflow rather than an option, so these run on
every write and their findings travel with the response.
"""

{GENERATED_NOTE}
from dataclasses import dataclass
from datetime import date, datetime
from typing import Any


@dataclass(frozen=True)
class Finding:
    """One rule that did not hold."""

    code: str
    message: str
    field: str
    severity: str = "error"


def _is_future(value: Any) -> bool:
    """Whether a date or datetime is after now, comparing like with like."""
    if isinstance(value, datetime):
        from datetime import UTC

        now = datetime.now(UTC)
        # A naive datetime cannot be compared with an aware one, and which of
        # the two arrives depends on the client rather than on this module.
        if value.tzinfo is None:
            value = value.replace(tzinfo=UTC)
        return value > now
    if isinstance(value, date):
        from datetime import UTC

        return value > datetime.now(UTC).date()
    return False


def validate(value: Any) -> list[Finding]:
    """Run every rule. Returns findings; an empty list means the record is sound."""
    findings: list[Finding] = []
{chr(10).join(checks)}
    return findings


def blocking(findings: list[Finding]) -> list[Finding]:
    """The findings that must stop a write, as opposed to warn about it."""
    return [f for f in findings if f.severity == "error"]
'''


def _permissions(spec: ModuleSpec) -> str:
    return f'''{HEADER}"""{_doc(spec.display_name)} permissions.

Registered rather than merely referenced: a permission the registry has never
heard of is denied to everyone except an administrator, and a test run as an
administrator cannot see the difference.
"""

{GENERATED_NOTE}
from app.core.permissions import Role, permission_registry

{spec.key.upper()}_PERMISSIONS: dict[str, Role] = {{
    "{spec.key}.read": Role.VIEWER,
    "{spec.key}.write": Role.EDITOR,
    "{spec.key}.delete": Role.MANAGER,
}}


def register_{spec.key}_permissions() -> None:
    """Register this module's permissions with the platform registry.

    Called from ``on_startup`` in this package's ``__init__``, which is the
    hook the module loader runs once the module is loaded.
    """
    permission_registry.register_module_permissions({spec.key!r}, {spec.key.upper()}_PERMISSIONS)
'''


def _repository(spec: ModuleSpec) -> str:
    entity = spec.entity
    if entity.project_scoped:
        abc_import = "from collections.abc import Collection\n"
        within_param = "        within: Collection[uuid.UUID] | None = None,\n"
        within_doc = (
            "\n"
            "        ``within`` is the set of projects the caller may reach. ``None``\n"
            "        means unrestricted, which the router only passes for an\n"
            "        administrator; an empty set returns nothing rather than everything.\n"
            "        Both filters apply before counting, so the total never counts rows\n"
            "        the caller cannot see.\n"
        )
        scope = (
            "        if project_id is not None:\n"
            f"            stmt = stmt.where({spec.class_name}.project_id == project_id)\n"
            "        if within is not None:\n"
            f"            stmt = stmt.where({spec.class_name}.project_id.in_(list(within)))\n"
        )
    else:
        abc_import = within_param = within_doc = scope = ""
    return f'''{HEADER}"""{_doc(spec.display_name)} data access."""

{GENERATED_NOTE}{REFRESHED_NOTE}
import uuid
{abc_import}
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.{spec.key}.models import {spec.class_name}


class {spec.class_name}Repository:
    """Reads and writes for {spec.table_name}."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    async def list_page(
        self,
        project_id: uuid.UUID | None = None,
{within_param}        limit: int = 100,
        offset: int = 0,
    ) -> tuple[list[{spec.class_name}], int]:
        """One page, plus the total the page was taken from.

        The total is counted rather than inferred from the page length, so a
        caller can tell a short last page from an empty result.
{within_doc}        """
        stmt = select({spec.class_name})
{scope}        count_stmt = select(func.count()).select_from(stmt.subquery())
        total = int((await self.session.execute(count_stmt)).scalar_one())
        stmt = stmt.order_by({spec.class_name}.created_at.desc()).limit(limit).offset(offset)
        rows = list((await self.session.execute(stmt)).scalars().all())
        return rows, total

    async def get(self, record_id: uuid.UUID) -> {spec.class_name} | None:
        return await self.session.get({spec.class_name}, record_id)

    async def add(self, record: {spec.class_name}) -> {spec.class_name}:
        self.session.add(record)
        await self.session.flush()
        return record

    async def delete(self, record: {spec.class_name}) -> None:
        await self.session.delete(record)
        await self.session.flush()
'''


def _service(spec: ModuleSpec) -> str:
    if spec.entity.project_scoped:
        abc_import = "from collections.abc import Collection\n"
        list_page = (
            "    async def list_page(\n"
            "        self,\n"
            "        project_id: uuid.UUID | None = None,\n"
            "        within: Collection[uuid.UUID] | None = None,\n"
            "        limit: int = 100,\n"
            "        offset: int = 0,\n"
            f"    ) -> tuple[list[{spec.class_name}], int]:\n"
            "        return await self.repo.list_page(project_id=project_id, within=within, limit=limit, offset=offset)\n"
        )
    else:
        abc_import = ""
        list_page = (
            "    async def list_page(\n"
            "        self, project_id: uuid.UUID | None = None, limit: int = 100, offset: int = 0\n"
            f"    ) -> tuple[list[{spec.class_name}], int]:\n"
            "        return await self.repo.list_page(project_id=project_id, limit=limit, offset=offset)\n"
        )
    name = spec.class_name
    local_imports = [
        f"from app.modules.{spec.key}.models import {name}\n",
        f"from app.modules.{spec.key}.repository import {name}Repository\n",
        f"from app.modules.{spec.key}.schemas import {name}Create, {name}Update\n",
        f"from app.modules.{spec.key}.validators import Finding, blocking, validate\n",
    ]
    link_fields = spec.link_fields
    if link_fields:
        project_of_new = "payload.project_id" if spec.entity.project_scoped else "None"
        project_of_record = "record.project_id" if spec.entity.project_scoped else "None"
        targets = ", ".join(f"{f.name!r}: {f.target!r}" for f in link_fields)
        local_imports.append("from app.modules.module_builder import links\n")
        link_table = f"""
# Each link field and the kind of record it points at. A link is checked
# against what the caller may see, so an id from a project they cannot reach,
# or a record in another project than this one, is refused rather than stored.
LINKS: dict[str, str] = {{{targets}}}
"""
        create_def = (
            "    async def create(\n"
            f"        self, payload: {name}Create, user_id: object = None\n"
            f"    ) -> tuple[{name}, list[Finding]]:\n"
            "        findings = validate(payload)\n"
            f"        findings += await self._link_findings({project_of_new}, payload.model_dump(), user_id)\n"
        )
        update_def = (
            "    async def update(\n"
            f"        self, record: {name}, payload: {name}Update, user_id: object = None\n"
            f"    ) -> tuple[{name}, list[Finding]]:\n"
        )
        update_links = (
            "        # Only the links this write changes. One set earlier that has since\n"
            "        # left the caller's sight is not this write's to refuse.\n"
            f"        findings += await self._link_findings({project_of_record}, changes, user_id)\n"
        )
        link_method = '''
    async def _link_findings(
        self, project_id: uuid.UUID | None, values: dict[str, object], user_id: object
    ) -> list[Finding]:
        """Refusals for links to records the caller may not see, or in another project."""
        chosen = {field: (target, values[field]) for field, target in LINKS.items() if field in values}
        if not chosen:
            return []
        problems = await links.link_problems(self.repo.session, user_id, project_id, chosen)
        return [Finding(code=code, message=message, field=field) for field, code, message in problems]
'''
    else:
        link_table = update_links = link_method = ""
        create_def = (
            f"    async def create(self, payload: {name}Create) -> tuple[{name}, list[Finding]]:\n"
            "        findings = validate(payload)\n"
        )
        update_def = (
            "    async def update(\n"
            f"        self, record: {name}, payload: {name}Update\n"
            f"    ) -> tuple[{name}, list[Finding]]:\n"
        )
    return f'''{HEADER}"""{_doc(spec.display_name)} business logic."""

{GENERATED_NOTE}{REFRESHED_NOTE}
import uuid
{abc_import}
from sqlalchemy.ext.asyncio import AsyncSession

{_first_party(*local_imports)}{link_table}

class ValidationRefused(Exception):
    """A write that the module's own rules will not allow."""

    def __init__(self, findings: list[Finding]) -> None:
        self.findings = findings
        super().__init__("; ".join(f"{{f.code}}: {{f.message}}" for f in findings))


class {spec.class_name}Service:
    """The operations the router exposes, with validation attached to writes."""

    def __init__(self, session: AsyncSession) -> None:
        self.repo = {spec.class_name}Repository(session)

{list_page}
    async def get(self, record_id: uuid.UUID) -> {spec.class_name} | None:
        return await self.repo.get(record_id)

{create_def}        if blocking(findings):
            raise ValidationRefused(blocking(findings))
        record = {spec.class_name}(**payload.model_dump())
        await self.repo.add(record)
        return record, findings

{update_def}        # Validate the record as it will be, not the patch on its own: a rule
        # about two fields cannot be judged from whichever one was sent.
        changes = payload.model_dump(exclude_unset=True)
        merged = _Merged(record, changes)
        findings = validate(merged)
{update_links}        if blocking(findings):
            raise ValidationRefused(blocking(findings))
        for key, value in changes.items():
            setattr(record, key, value)
        return record, findings

    async def delete(self, record: {spec.class_name}) -> None:
        await self.repo.delete(record)
{link_method}

class _Merged:
    """A read-only view of a record with pending changes applied.

    Used to validate an update before it is written, so a refused update leaves
    the row untouched rather than needing a rollback.
    """

    def __init__(self, record: object, changes: dict[str, object]) -> None:
        self._record = record
        self._changes = changes

    def __getattr__(self, name: str) -> object:
        if name in self._changes:
            return self._changes[name]
        return getattr(self._record, name)
'''


def _router(spec: ModuleSpec) -> str:
    """The HTTP API, with the access rule that fits the record.

    A project-scoped record is reachable only through a project the caller may
    reach, by the same rule the rest of the platform applies: owner, team
    member or administrator, through ``verify_project_access`` and its set
    form ``accessible_project_ids``. Refusals answer 404 with the same body as
    a record that does not exist, so ids from other projects cannot be probed.

    A record that belongs to no project has no narrower scope to check, so the
    module permission is the whole rule, as for any platform-wide register.
    """
    entity = spec.entity
    name = spec.class_name
    scoped = entity.project_scoped
    has_links = bool(spec.link_fields)
    export = spec.features.export

    def scoped_rows(limit: str, offset: str, total: str = "total") -> str:
        return f"""    within = None
    if project_id is not None:
        await verify_project_access(project_id, user_id, db)
    else:
        # The projects this caller may reach. None for an administrator, who is
        # not restricted; an empty set for someone with no projects, which
        # lists nothing rather than everything.
        within = await accessible_project_ids(db, user_id)
    rows, {total} = await {name}Service(db).list_page(
        project_id=project_id, within=within, limit={limit}, offset={offset}
    )
"""

    if scoped:
        dependencies = (
            "from app.dependencies import (\n"
            "    CurrentUserId,\n"
            "    RequirePermission,\n"
            "    SessionDep,\n"
            "    accessible_project_ids,\n"
            "    verify_project_access,\n"
            ")\n"
        )
        # The models module rather than the class: a record class called
        # Path or Query would shadow a name this router already imports.
        models_import = [f"from app.modules.{spec.key} import models\n"]
        access = f'''
# Every record belongs to a project, and the module permission says nothing
# about which projects. So each route also applies the platform's project
# access rule (owner, team member or administrator) and answers 404 where it
# refuses: the same answer as for a record that does not exist, so a caller
# cannot learn which ids exist in projects they cannot see.


async def _reachable(service: {name}Service, record_id: uuid.UUID, user_id: str, db: SessionDep) -> models.{name}:
    """The record, if it exists and the caller may reach its project.

    ``verify_project_access`` refuses with "Project not found", which would
    tell the caller that the record exists. Its 404 is replaced with the one a
    missing record gets, so both refusals read the same.
    """
    record = await service.get(record_id)
    if record is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "not found")
    try:
        await verify_project_access(record.project_id, user_id, db)
    except HTTPException as exc:
        if exc.status_code != status.HTTP_404_NOT_FOUND:
            raise
        raise HTTPException(status.HTTP_404_NOT_FOUND, "not found") from None
    return record
'''
        user_param = "    user_id: CurrentUserId,\n"
        list_params = (
            "    db: SessionDep,\n"
            "    user_id: CurrentUserId,\n"
            '    project_id: uuid.UUID | None = Query(None, description="Restrict to one project"),\n'
        )
        list_body = scoped_rows("limit", "offset")
        export_params = list_params
        export_body = scoped_rows("MAX_EXPORT_ROWS", "0")
        get_load = f"    record = await _reachable({name}Service(db), record_id, user_id, db)\n"
        create_check = (
            "    # The project in the body is the caller's claim, not a fact. A project\n"
            "    # they cannot reach answers 404, exactly as one that does not exist.\n"
            "    await verify_project_access(payload.project_id, user_id, db)\n"
        )
        service_load = (
            f"    service = {name}Service(db)\n"
            "    # Before validation, so a refused record answers 404 and never a 422\n"
            "    # that would confirm it exists. The update schema has no project_id,\n"
            "    # so a record cannot be moved into a project from here.\n"
            "    record = await _reachable(service, record_id, user_id, db)\n"
        )
        delete_load = (
            f"    service = {name}Service(db)\n    record = await _reachable(service, record_id, user_id, db)\n"
        )
    else:
        if has_links or export:
            # Links are checked, and exported links labelled, as the caller sees them.
            dependencies = "from app.dependencies import CurrentUserId, RequirePermission, SessionDep\n"
        else:
            dependencies = "from app.dependencies import RequirePermission, SessionDep\n"
        models_import = []
        export_params = "    db: SessionDep,\n    user_id: CurrentUserId,\n"
        export_body = f"    rows, total = await {name}Service(db).list_page(limit=MAX_EXPORT_ROWS)\n"
        access = """
# These records belong to no project, so there is no narrower scope to check:
# the module permission is the whole access rule, as for any register that is
# shared across the installation. A project-scoped module also checks access to
# the record's project on every route.
"""
        user_param = "    user_id: CurrentUserId,\n" if has_links else ""
        list_params = "    db: SessionDep,\n"
        list_body = f"    rows, total = await {name}Service(db).list_page(limit=limit, offset=offset)\n"
        missing = '    if record is None:\n        raise HTTPException(status.HTTP_404_NOT_FOUND, "not found")\n'
        get_load = f"    record = await {name}Service(db).get(record_id)\n{missing}"
        create_check = ""
        service_load = f"    service = {name}Service(db)\n    record = await service.get(record_id)\n{missing}"
        delete_load = service_load

    service_names = ", ".join(sorted([f"{name}Service", "ValidationRefused"]))
    fastapi_names = (
        "APIRouter, Depends, HTTPException, Query, Response, status"
        if export
        else ("APIRouter, Depends, HTTPException, Query, status")
    )
    local_imports = [
        *models_import,
        f"from app.modules.{spec.key}.schemas import (\n    {name}Create,\n    {name}List,\n    {name}Read,\n"
        f"    {name}Update,\n)\n",
        f"from app.modules.{spec.key}.service import {service_names}\n",
    ]
    if export:
        local_imports.append("from app.modules.module_builder.export import MAX_EXPORT_ROWS, export_response\n")
    user_arg = ", user_id=user_id" if has_links else ""
    export_route = (
        f'''

@router.get("/export", summary={_lit(f"Download {entity.plural_name.lower()} as a spreadsheet")})
async def export_records(
{export_params}    fmt: str = Query("csv", alias="format", pattern="^(csv|xlsx)$"),
    _perm: None = Depends(RequirePermission("{spec.key}.read")),
) -> Response:
    """The records the list would show, as CSV or Excel.

    The same access rule as the list, so the file never holds a row the
    screen would not. Declared before ``/{{record_id}}`` so the path is not
    read as an id.
    """
{export_body}    return await export_response(db, user_id, Path(__file__).parent / "spec.json", rows, fmt, total=total)
'''
        if export
        else ""
    )
    return f'''{HEADER}"""{_doc(spec.display_name)} HTTP API."""

{GENERATED_NOTE}{REFRESHED_NOTE}
import json
import uuid
from pathlib import Path

from fastapi import {fastapi_names}

{dependencies}{_first_party(*local_imports)}
router = APIRouter()
{access}

@router.get("/ui-spec", summary="The screen description this module renders from")
async def ui_spec() -> dict:
    """Return the module specification.

    The frontend is a compiled bundle, so a module installed at runtime cannot
    ship a screen of its own. It ships this instead, and the platform renders
    the list, the detail and the form from it.
    """
    path = Path(__file__).parent / "spec.json"
    if not path.is_file():
        raise HTTPException(status.HTTP_404_NOT_FOUND, "this module carries no ui spec")
    return json.loads(path.read_text(encoding="utf-8"))


@router.get("", response_model={name}List, summary={_lit(f"List {entity.plural_name.lower()}")})
async def list_records(
{list_params}    limit: int = Query(100, ge=1, le=500),
    offset: int = Query(0, ge=0),
    _perm: None = Depends(RequirePermission("{spec.key}.read")),
) -> {name}List:
{list_body}    return {name}List(items=[{name}Read.model_validate(r) for r in rows], total=total)
{export_route}

@router.get("/{{record_id}}", response_model={name}Read, summary={_lit(f"One {entity.display_name.lower()}")})
async def get_record(
    record_id: uuid.UUID,
    db: SessionDep,
{user_param}    _perm: None = Depends(RequirePermission("{spec.key}.read")),
) -> {name}Read:
{get_load}    return {name}Read.model_validate(record)


@router.post("", response_model={name}Read, status_code=status.HTTP_201_CREATED)
async def create_record(
    payload: {name}Create,
    db: SessionDep,
{user_param}    _perm: None = Depends(RequirePermission("{spec.key}.write")),
) -> {name}Read:
{create_check}    try:
        record, _findings = await {name}Service(db).create(payload{user_arg})
    except ValidationRefused as exc:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=[{{"code": f.code, "message": f.message, "field": f.field}} for f in exc.findings],
        ) from exc
    await db.commit()
    await db.refresh(record)
    return {name}Read.model_validate(record)


@router.patch("/{{record_id}}", response_model={name}Read)
async def update_record(
    record_id: uuid.UUID,
    payload: {name}Update,
    db: SessionDep,
{user_param}    _perm: None = Depends(RequirePermission("{spec.key}.write")),
) -> {name}Read:
{service_load}    try:
        record, _findings = await service.update(record, payload{user_arg})
    except ValidationRefused as exc:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=[{{"code": f.code, "message": f.message, "field": f.field}} for f in exc.findings],
        ) from exc
    await db.commit()
    await db.refresh(record)
    return {name}Read.model_validate(record)


@router.delete("/{{record_id}}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_record(
    record_id: uuid.UUID,
    db: SessionDep,
{user_param}    # Deleting is a manager's action, as it is everywhere else in the platform.
    # Whoever may correct a record is not automatically whoever may remove it.
    _perm: None = Depends(RequirePermission("{spec.key}.delete")),
) -> None:
{delete_load}    await service.delete(record)
    await db.commit()
'''


def _locale(spec: ModuleSpec) -> str:
    """English strings for the generated screen.

    English only, on purpose. The platform ships 29 locales and a machine
    translation nobody read is worse than an untranslated string: the reader
    cannot tell it was never checked. The generated screen falls back to
    English until a person translates it.
    """
    payload = {
        spec.key: {
            "title": spec.display_name,
            "description": spec.description,
            "entity": spec.entity.display_name,
            "entityPlural": spec.entity.plural_name,
            "fields": {f.name: f.label for f in spec.entity.fields},
            "help": {f.name: f.help_text for f in spec.entity.fields if f.help_text},
            "rules": {r.code: r.message for r in spec.rules},
        }
    }
    status = spec.features.status
    if status is not None:
        payload[spec.key]["states"] = {s.code: s.label for s in status.states}
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _tests_conftest() -> str:
    """Let the generated tests run on their own, outside platform startup.

    The module lives in the instance's runtime module root, which is only on
    the import path once the platform has attached it. A developer running
    ``pytest`` against the module directory has not been through startup, so
    the tests attach the root themselves.
    """
    return f'''{HEADER}"""Make this module importable when its tests run on their own."""

{GENERATED_NOTE}
from pathlib import Path

# tests/ -> <module>/ -> the runtime module root that holds it.
RUNTIME_ROOT = Path(__file__).resolve().parents[2]


def pytest_configure() -> None:
    from app.core.module_runtime_root import attach_runtime_root

    attach_runtime_root(RUNTIME_ROOT, create=False)
'''


def _tests(spec: ModuleSpec) -> str:
    """Tests that come with the module, exercising its own rules.

    Generated from the same rules the validator was generated from, so they
    check the rendering rather than restating it: each one builds a record that
    breaks exactly one rule and asserts that rule fires.
    """
    cases = []
    for rule in spec.rules:
        cases.append(
            f"    def test_{rule.code.lower()}_fires(self) -> None:\n"
            f"        findings = validate(_breaking({rule.code!r}))\n"
            f"        assert {rule.code!r} in [f.code for f in findings]\n"
        )
    field_defaults = ", ".join(f"{f.name}={_sample_source(f)}" for f in spec.entity.fields)
    status = spec.features.status
    if status is not None:
        field_defaults += f", {STATUS_COLUMN}={status.states[0].code!r}"
        cases.append(
            "    def test_an_unknown_status_is_refused(self) -> None:\n"
            "        record = _sound()\n"
            f"        record.{STATUS_COLUMN} = 'definitely-not-a-state'\n"
            f"        assert {STATUS_RULE_CODE!r} in [f.code for f in validate(record)]\n"
        )
    uuid_import = "import uuid\n" if spec.link_fields else ""
    return f'''{HEADER}"""Tests for {_doc(spec.display_name)}."""

{GENERATED_NOTE}
{uuid_import}from datetime import UTC, datetime, timedelta  # noqa: F401
from types import SimpleNamespace

from app.modules.{spec.key}.validators import validate

RULES = {[r.model_dump(mode="json") for r in spec.rules]!r}


def _sound() -> SimpleNamespace:
    """A record every rule accepts."""
    return SimpleNamespace({field_defaults})


def _breaking(code: str) -> SimpleNamespace:
    """A sound record with exactly one rule broken."""
    record = _sound()
    rule = next(r for r in RULES if r["code"] == code)
    field, kind = rule["field"], rule["kind"]
    if kind == "required":
        setattr(record, field, None)
    elif kind in {{"positive"}}:
        setattr(record, field, -1)
    elif kind == "range":
        low, high = rule.get("min_value"), rule.get("max_value")
        setattr(record, field, (low - 1) if low is not None else (high + 1))
    elif kind == "one_of":
        setattr(record, field, "definitely-not-an-option")
    elif kind == "not_future":
        # No local import here. Binding datetime names inside one branch makes
        # them local to the whole function, and the order branch below then
        # raises UnboundLocalError on a name the module already imported.
        current = getattr(record, field)
        ahead = datetime.now(UTC) + timedelta(days=365)
        setattr(record, field, ahead if isinstance(current, datetime) else ahead.date())
    elif kind == "order":
        # One day past the field it must not exceed.
        setattr(record, field, getattr(record, rule["other_field"]) + timedelta(days=1))
    return record


class TestRules:
    def test_a_sound_record_passes_every_rule(self) -> None:
        assert validate(_sound()) == []

{chr(10).join(cases)}
    def test_every_rule_is_covered(self) -> None:
        """The count is the point: a rule with no test looks the same as one that passes."""
        tested = {{name.removeprefix("test_").removesuffix("_fires").upper() for name in dir(TestRules) if name.endswith("_fires")}}
        assert tested == {{r["code"] for r in RULES}}
'''


def _sample_source(field: FieldSpec) -> str:
    """Python source for a value every rule accepts.

    Source rather than a value: a date has no literal form that ``repr`` can
    put in a generated file, and a placeholder string in its place would give
    the generated tests a record that fails on a type error rather than on the
    rule under test.

    Numbers start at 1 so a ``positive`` rule holds; a ``range`` rule can still
    exclude 1, which the range case in ``_breaking`` accounts for by moving
    outside the bound rather than assuming the sound value is inside it.
    """
    if field.type == "integer":
        return "1"
    if field.type in {"number", "money"}:
        return "1"
    if field.type == "boolean":
        return "True"
    # Yesterday, not today: it satisfies ``not_future`` without depending on
    # the clock crossing midnight mid-run, and leaves room for an ``order``
    # rule to place a later field after it.
    if field.type == "date":
        return "(datetime.now(UTC) - timedelta(days=2)).date()"
    if field.type == "datetime":
        return "datetime.now(UTC) - timedelta(days=2)"
    if field.type == "select":
        return repr(field.options[0])
    if field.type == "link":
        return "uuid.uuid4()"
    if field.type == "long_text":
        return repr(f"About {field.label.lower()}")
    return repr(field.label)


def _readme(spec: ModuleSpec) -> str:
    rows = "\n".join(
        f"| `{f.name}` | {f.label} | {f'link to {f.target}' if f.type == 'link' else f.type} | "
        f"{'yes' if f.required else 'no'} |"
        for f in spec.entity.fields
    )
    rules = "\n".join(f"- `{r.code}` ({r.severity}): {r.message}" for r in spec.rules)
    features = spec.features
    extra_api = ""
    if features.export:
        extra_api += "- `GET /export?format=csv|xlsx` the list as a spreadsheet\n"
    status_section = ""
    if features.status is not None:
        states = "\n".join(f"- `{s.code}` {s.label}{' (done)' if s.done else ''}" for s in features.status.states)
        status_section = f"\n## Status\n\nA new record starts as `{features.status.states[0].code}`.\n\n{states}\n"
    if features.due is not None:
        status_section += (
            f"\n## Deadline\n\n`{features.due.field}` is the deadline. It shows in the deadline register and is "
            f"reminded {features.due.remind_days_before} day(s) before.\n"
        )
    if features.comments:
        status_section += f"\n## Comments\n\nRecords take comments as `built.{spec.key}`.\n"
    return f"""# {spec.display_name}

{spec.description or "Generated with the OpenConstructionERP module builder."}

This module was generated from a specification rather than written by hand.
`spec.json` beside this file is that specification, and it is also what the
platform renders the screen from.

## Record: {spec.entity.display_name}

| Field | Label | Type | Required |
|---|---|---|---|
{rows}

## Rules

{rules}
{status_section}
## API

Mounted at `{spec.url_prefix}`.

- `GET /ui-spec` the screen description
- `GET /` list, `GET /{{id}}` one
- `POST /` create, `PATCH /{{id}}` update, `DELETE /{{id}}` remove
{extra_api}
Reading needs `{spec.key}.read`, writing needs `{spec.key}.write`.
"""
